(function(){
'use strict';
var KEY='bah-pages-v4';
var $=function(id){return document.getElementById(id)};
var state={cfg:{provider:'free_anonymous',protocol:'openai_chat',baseUrl:'https://text.pollinations.ai/openai',apiKey:'',model:'openai',thinking:'auto',mode:'chat',maxTokens:4096,timeout:120000},sessions:[],session:null,busy:false,controller:null,activity:[],workspace:[]};
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function now(){return new Date().toISOString()}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function clean(s){return String(s||'').replace(/https?:\/\/(?:www\.)?googleusercontent\.com\/(?:immersive_entry_chip|card_content)\/\d+/gi,'').trim()}
function cap(s){s=String(s||'');return s.charAt(0).toUpperCase()+s.slice(1)}
function save(){try{var c=Object.assign({},state.cfg,{apiKey:''});localStorage.setItem(KEY,JSON.stringify({cfg:c,sessions:state.sessions.slice(0,50),active:state.session&&state.session.id}))}catch(e){}}
function load(){try{var d=JSON.parse(localStorage.getItem(KEY)||'{}');if(d.cfg)state.cfg=Object.assign({},state.cfg,d.cfg);state.cfg.apiKey='';state.sessions=Array.isArray(d.sessions)?d.sessions:[];state.session=state.sessions.find(function(x){return x.id===d.active})||state.sessions[0]||null}catch(e){}if(!state.session)newChat(true);render()}
function newChat(silent){state.session={id:uid(),title:'New Chat',createdAt:now(),updatedAt:now(),messages:[]};state.sessions.unshift(state.session);state.sessions=state.sessions.slice(0,50);save();render();if(!silent)log('New chat','Started a new conversation')}
function render(){if(!state.session)return;$('sessionTitle').textContent=state.session.title;$('modelPill').textContent='Model: '+(state.cfg.model||'auto');$('thinkPill').textContent='Thinking: '+cap(state.cfg.thinking);$('thinkBtn').textContent='Thinking: '+cap(state.cfg.thinking);$('modeBtn').textContent='Mode: '+cap(state.cfg.mode);$('statusLeft').textContent='Provider: '+(state.cfg.provider==='free_anonymous'?'Free Anonymous':state.cfg.provider);renderChats();renderMessages();renderActivity()}
function renderChats(){var h='';state.sessions.slice(0,30).forEach(function(s){h+='<div class="listItem '+(state.session.id===s.id?'active':'')+'" data-sid="'+esc(s.id)+'"><div class="small">'+esc(s.title)+'</div><div class="tiny">'+new Date(s.updatedAt).toLocaleString()+'</div></div>'});$('chatList').innerHTML=h||'<div class="tiny">No chats</div>';$('leftDrawerBody').innerHTML=h||'<div class="tiny">No chats</div>';document.querySelectorAll('[data-sid]').forEach(function(b){b.onclick=function(){var s=state.sessions.find(function(x){return x.id===b.dataset.sid});if(s){state.session=s;save();render();closeDrawer('leftDrawer');closeDrawer('rightDrawer')}}})}
function renderMessages(){var m=state.session.messages||[];if(!m.length){$('inner').innerHTML='<div class="empty"><div class="emptyCard"><div class="emptyTitle">Free AI Coding Agent</div><div class="emptySub">No site login. Use anonymous free AI, or configure Gemini Web2API or another OpenAI-compatible endpoint.</div><div class="quick"><button data-q="Create a responsive HTML Snake game for Android Chrome."><b>Build code</b><span>Generate runnable code</span></button><button data-q="Review this code and find bugs."><b>Review code</b><span>Paste code in chat</span></button><button data-q="Explain Python async programming simply."><b>Explain</b><span>Learn a concept</span></button><button data-q="How do I connect gemini-web2api on 127.0.0.1:8081?"><b>Local API</b><span>Connection guidance</span></button></div></div></div>';document.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){$('composer').value=b.dataset.q;size();$('composer').focus()}});return}$('inner').innerHTML=m.map(messageHTML).join('');bindCopy();requestAnimationFrame(function(){$('messages').scrollTop=$('messages').scrollHeight})}
function messageHTML(m){var r=m.role==='assistant'?'ai':m.role==='user'?'user':'error';var b=r==='ai'?markdown(m.content):'<div class="md"><p>'+esc(clean(m.content)).replace(/\n/g,'<br>')+'</p></div>';return '<article class="msg '+r+'"><div class="meta"><span class="avatar">'+(r==='ai'?'AI':r==='user'?'U':'!')+'</span><span>'+(r==='ai'?'AI':r==='user'?'You':'Error')+'</span><span>·</span><span>'+new Date(m.time||Date.now()).toLocaleTimeString()+'</span></div><div class="bubble">'+b+'</div></article>'}
function markdown(s){s=esc(clean(s));s=s.replace(/\x60\x60\x60([\w.+-]*)\n([\s\S]*?)\x60\x60\x60/g,function(_,lang,code){return '<div class="code"><div class="codeHead"><span>'+esc(lang||'text')+'</span><button data-copy="'+encodeURIComponent(code)+'">Copy</button></div><pre>'+code+'</pre></div>'});s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n\n+/g,'</p><p>').replace(/\n/g,'<br>');return '<div class="md"><p>'+s+'</p></div>'}
function bindCopy(){document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){if(navigator.clipboard)navigator.clipboard.writeText(decodeURIComponent(b.dataset.copy));b.textContent='Copied';setTimeout(function(){b.textContent='Copy'},700)}})}
function log(title,detail){state.activity.unshift({t:Date.now(),title:title,detail:detail||''});state.activity=state.activity.slice(0,80);renderActivity()}
function renderActivity(){var h=state.activity.map(function(a){return '<div class="activityItem"><div class="activityTime">'+new Date(a.t).toLocaleTimeString()+'</div><div class="activityTitle">'+esc(a.title)+'</div><div class="activityDetail">'+esc(a.detail)+'</div></div>'}).join('')||'<div class="tiny">No activity yet.</div>';$('activityList').innerHTML=h;$('rightDrawerBody').innerHTML=h}
function openDrawer(id){$(id).classList.add('open');if(id==='rightDrawer')renderActivity()}
function closeDrawer(id){$(id).classList.remove('open')}
function addUser(t){state.session.messages.push({id:uid(),role:'user',time:now(),content:clean(t)});state.session.updatedAt=now();if(state.session.messages.length===1)state.session.title=t.length>42?t.slice(0,39)+'...':t;save();renderMessages();renderChats()}
function beginAssistant(){var m={id:uid(),role:'assistant',time:now(),content:''};state.session.messages.push(m);state.session.updatedAt=now();save();var n=document.createElement('article');n.className='msg ai';n.innerHTML='<div class="meta"><span class="avatar">AI</span><span>AI</span><span>·</span><span>'+new Date().toLocaleTimeString()+'</span></div><div class="bubble"><div class="streamText"></div></div>';$('inner').appendChild(n);$('messages').scrollTop=$('messages').scrollHeight;return{m:m,node:n,text:n.querySelector('.streamText'),last:0}}
function updateStream(a,s,force){a.m.content=s;var t=Date.now();if(force||t-a.last>60){a.text.textContent=clean(s);a.last=t;$('messages').scrollTop=$('messages').scrollHeight}}
function finish(a){a.node.outerHTML=messageHTML(a.m);bindCopy();state.session.updatedAt=now();save()}
function isGeminiLocal(){var b=(state.cfg.baseUrl||'').replace(/\/+$/,'');return /^http:\/\/(?:127\.0\.0\.1|localhost|\[::1\])(?::\d+)?\/v1$/i.test(b)&&/^gemini-/i.test(state.cfg.model||'')}
function requestModel(){var m=(state.cfg.model||'openai').split('@think=')[0];if(isGeminiLocal()){if(state.cfg.thinking==='high')return m+'@think=0';if(state.cfg.thinking==='medium')return m+'@think=2';if(state.cfg.thinking==='low')return m+'@think=4'}return m}
function requestUrl(){var b=(state.cfg.baseUrl||'').replace(/\/+$/,'');if(state.cfg.provider==='free_anonymous')return b||'https://text.pollinations.ai/openai';if(/\/chat\/completions$/.test(b)||/\/openai$/.test(b)||/\/messages$/.test(b))return b;if(state.cfg.provider==='anthropic'||state.cfg.protocol==='anthropic_messages')return /\/v1$/.test(b)?b+'/messages':b+'/v1/messages';return /\/v1$/.test(b)?b+'/chat/completions':b+'/v1/chat/completions'}
function headers(){var h={'Content-Type':'application/json','Accept':'text/event-stream'};if(state.cfg.apiKey)h.Authorization='Bearer '+state.cfg.apiKey;return h}
function apiMessages(){var a=[{role:'system',content:'You are a helpful AI coding assistant. Answer directly. When code is requested, provide complete runnable code.'}];state.session.messages.forEach(function(m){if(m.role==='user'||m.role==='assistant')a.push({role:m.role,content:m.content})});return a}
async function callAI(a){var isAnth=(state.cfg.provider==='anthropic'||state.cfg.protocol==='anthropic_messages')&&!isGeminiLocal();var url=requestUrl(),body;if(isAnth)body={model:state.cfg.model,max_tokens:Number(state.cfg.maxTokens)||4096,system:'You are a helpful AI coding assistant.',messages:apiMessages().filter(function(x){return x.role!=='system'}),stream:true};else body={model:requestModel(),messages:apiMessages(),stream:true,max_tokens:Number(state.cfg.maxTokens)||4096};log('Request',url+' · '+body.model);var c=new AbortController();state.controller=c;var timer=setTimeout(function(){if(!c.signal.aborted)c.abort('timeout')},Number(state.cfg.timeout)||120000),r;try{var h=headers();if(isAnth&&state.cfg.apiKey){h['x-api-key']=state.cfg.apiKey;h['anthropic-version']='2023-06-01';delete h.Authorization}r=await fetch(url,{method:'POST',headers:h,body:JSON.stringify(body),signal:c.signal,cache:'no-store'})}catch(e){clearTimeout(timer);if(c.signal.aborted)throw new Error(c.signal.reason==='timeout'?'Request timed out.':'Generation stopped.');throw new Error('Failed to fetch. Check endpoint/CORS or Chrome local-network permission.')}clearTimeout(timer);if(!r.ok){var tx=await r.text();throw new Error('HTTP '+r.status+(tx?': '+tx.slice(0,900):''))}var ct=(r.headers.get('content-type')||'').toLowerCase();if(!r.body||ct.indexOf('application/json')>=0){var j=await r.json();a.m.content=clean((j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content)||j.output_text||'');finish(a);return}var reader=r.body.getReader(),dec=new TextDecoder(),buf='',done=false;while(!done){var p=await reader.read();done=p.done;if(p.value)buf+=dec.decode(p.value,{stream:true});var chunks=buf.split('\n\n');buf=chunks.pop()||'';for(var i=0;i<chunks.length;i++){var lines=chunks[i].split('\n');for(var j=0;j<lines.length;j++){var line=lines[j].trim();if(line.indexOf('data:')!==0)continue;var raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;try{var ev=JSON.parse(raw),txt='';if(isAnth){if(ev.type==='content_block_delta'&&ev.delta&&ev.delta.type==='text_delta')txt=ev.delta.text||''}else{var d=ev.choices&&ev.choices[0]&&ev.choices[0].delta||{};txt=d.content||''}if(txt)updateStream(a,a.m.content+txt,false)}catch(e){}}}}updateStream(a,a.m.content,true);finish(a);log('Completed',a.m.content.length+' chars')}
async function send(){if(state.busy)return;var t=$('composer').value.trim();if(!t)return;if(t.charAt(0)==='/'){command(t);$('composer').value='';size();return}addUser(t);$('composer').value='';size();state.busy=true;$('sendBtn').disabled=true;$('stopBtn').style.display='inline-block';$('statePill').textContent='● Working';var a=beginAssistant();try{if(state.cfg.provider==='demo'){var s='Demo mode is active. Configure a real endpoint in Settings.';updateStream(a,s,true);finish(a)}else await callAI(a)}catch(e){a.m.content='Error: '+e.message;finish(a);log('Error',e.message)}finally{state.busy=false;state.controller=null;$('sendBtn').disabled=false;$('stopBtn').style.display='none';$('statePill').textContent='● Idle';save()}}
function stop(){if(state.controller){try{state.controller.abort('manual')}catch(e){}state.controller=null}}
function size(){var x=$('composer');x.style.height='auto';x.style.height=Math.min(150,x.scrollHeight)+'px'}
function modal(title,body,buttons){document.body.classList.add('modalOpen');$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalFoot').innerHTML='';(buttons||[{label:'Close',fn:closeModal}]).forEach(function(b){var x=document.createElement('button');x.className='btn'+(b.primary?' primary':'');x.textContent=b.label;x.onclick=b.fn;$('modalFoot').appendChild(x)});$('overlay').classList.add('open')}
function closeModal(){$('overlay').classList.remove('open');document.body.classList.remove('modalOpen')}
function settings(){var c=state.cfg;var body='<div class="grid2"><div class="field"><label>Provider</label><select id="sp" class="select"><option value="free_anonymous">Free Anonymous (No Login)</option><option value="openai_compatible">OpenAI Compatible</option><option value="anthropic">Anthropic</option><option value="demo">Demo</option></select></div><div class="field"><label>Protocol</label><select id="spr" class="select"><option value="openai_chat">OpenAI Chat</option><option value="anthropic_messages">Anthropic Messages</option></select></div><div class="field"><label>Base URL</label><input id="sb" class="input"></div><div class="field"><label>Model</label><input id="sm" class="input"></div><div class="field"><label>API key</label><input id="sk" class="input" type="password" placeholder="Not stored after reload"></div><div class="field"><label>Max output tokens</label><input id="sx" class="input" type="number" min="64"></div><div class="field"><label>Timeout ms</label><input id="st" class="input" type="number" min="5000"></div></div><div class="notice"><b>Free anonymous preset:</b> https://text.pollinations.ai/openai · model openai.<br><b>Gemini Web2API:</b> http://127.0.0.1:8081/v1 · OpenAI Chat · your exposed Gemini model.</div>';modal('Settings',body,[{label:'Cancel',fn:closeModal},{label:'Save',primary:true,fn:function(){state.cfg.provider=$('sp').value;state.cfg.protocol=$('spr').value;state.cfg.baseUrl=$('sb').value.replace(/\/+$/,'');state.cfg.model=$('sm').value.trim();state.cfg.apiKey=$('sk').value;state.cfg.maxTokens=Math.max(64,Number($('sx').value)||4096);state.cfg.timeout=Math.max(5000,Number($('st').value)||120000);save();render();closeModal();log('Settings saved',state.cfg.baseUrl)}}]);$('sp').value=c.provider;$('spr').value=c.protocol;$('sb').value=c.baseUrl;$('sm').value=c.model;$('sk').value=c.apiKey;$('sx').value=c.maxTokens;$('st').value=c.timeout}
function thinking(){var h='<div class="row">';['off','auto','low','medium','high','max'].forEach(function(v){h+='<button class="btn '+(state.cfg.thinking===v?'primary':'')+'" data-tv="'+v+'">'+cap(v)+'</button>'});h+='</div><div class="notice" style="margin-top:10px">For Gemini Web2API, High/Medium/Low map to @think=0/2/4.</div>';modal('Thinking',h);document.querySelectorAll('[data-tv]').forEach(function(b){b.onclick=function(){state.cfg.thinking=b.dataset.tv;save();render();closeModal()}})}
function mode(){var h='<div class="row">';['chat','plan','agent','review'].forEach(function(v){h+='<button class="btn '+(state.cfg.mode===v?'primary':'')+'" data-mv="'+v+'">'+cap(v)+'</button>'});h+='</div>';modal('Agent mode',h);document.querySelectorAll('[data-mv]').forEach(function(b){b.onclick=function(){state.cfg.mode=b.dataset.mv;save();render();closeModal()}})}
function compact(){var k=state.session.messages.slice(-10);state.session.messages=[{id:uid(),role:'system',time:now(),content:'Local context summary: '+k.map(function(m){return m.role+': '+m.content.slice(0,700)}).join(' | ')},...k];save();render();log('Context compacted','Kept recent messages.')}
function exportChat(){var b=new Blob([JSON.stringify(state.session,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='chat.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function openWorkspace(){var i=$('fileInput');i.onchange=async function(){state.workspace=[];for(var x=0;x<i.files.length&&x<80;x++){var f=i.files[x];if(f.size<=2097152)state.workspace.push({name:f.webkitRelativePath||f.name,content:await f.text()})}log('Workspace loaded',state.workspace.length+' files');i.value=''};i.setAttribute('webkitdirectory','');i.click()}
function command(s){var c=s.split(/\s+/)[0];if(c==='/help'){modal('Commands','<div class="notice">/new /settings /thinking /compact /clear /export /demo /local</div>');return}if(c==='/new'){newChat();return}if(c==='/settings'){settings();return}if(c==='/thinking'){thinking();return}if(c==='/compact'){compact();return}if(c==='/clear'){state.session.messages=[];save();render();return}if(c==='/export'){exportChat();return}if(c==='/demo'){state.cfg.provider='demo';save();render();return}if(c==='/local'){localPreset();return}}
$('sendBtn').onclick=send;$('stopBtn').onclick=stop;$('newBtn').onclick=function(){newChat()};$('leftNew').onclick=function(){newChat()};$('settingsBtn').onclick=settings;$('thinkBtn').onclick=thinking;$('modeBtn').onclick=mode;$('sessionMenu').onclick=chatMenu;$('attachBtn').onclick=openWorkspace;$('localBtn').onclick=localPreset;$('openLeft').onclick=function(){openDrawer('leftDrawer')};$('openRight').onclick=function(){openDrawer('rightDrawer')};$('modalClose').onclick=closeModal;$('overlay').onclick=function(e){if(e.target===$('overlay'))closeModal()};$('overlay').addEventListener('touchmove',function(e){if(e.target===$('overlay'))e.preventDefault()},{passive:false});$('clearActivity').onclick=function(){state.activity=[];renderActivity()};document.querySelectorAll('[data-close]').forEach(function(b){b.onclick=function(){closeDrawer(b.dataset.close)}});$('composer').addEventListener('input',size);$('composer').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});function chatMenu(){modal('Chat actions','<div class="row"><button class="btn" id="clearChat">Clear</button><button class="btn" id="compactChat">Compact</button><button class="btn" id="exportChat">Export</button></div>');$('clearChat').onclick=function(){state.session.messages=[];save();render();closeModal()};$('compactChat').onclick=function(){compact();closeModal()};$('exportChat').onclick=function(){exportChat();closeModal()}}function localPreset(){state.cfg.provider='openai_compatible';state.cfg.protocol='openai_chat';state.cfg.baseUrl='http://127.0.0.1:8081/v1';if(!/^gemini-/.test(state.cfg.model||''))state.cfg.model='gemini-3.7-flash';save();render();log('Gemini Web2API preset',state.cfg.baseUrl)}
load();render();log('Ready','Android + PC · local chat memory · lightweight streaming');if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});
})();